### ISSUE TITLE
Change front page text and buttons

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/crab-game#16]
Citizen Science Experiment

_Are shore crabs more visible to humans or their natural predators?_ TO BE REPLACED WITH GENERIC SENTENCE

Play this game to help scientists research the success of shore crab 
camouflage

Play           Results

**Comment by FIONACH** [comment]
Citizen Science Experiment

Can you spot the shore crabs in their different habitats? 

Play this game to help scientists research the success of shore crab 
camouflage

Play Results

**Comment by nebogeo** [comment]
The game server is now updated with most of these changes...
