### ISSUE TITLE
Change predator page text

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/crab-game#17]
Will you hunt as a predatory pollock or a hungry human?

They see the world differently....

Pollock
Dichromatic vision

Human
Trichromatic vision

**Comment by FIONACH** [comment]
Will you hunt as a predatory pollock or a hungry human?

They see the world differently....

Pollock
Dichromatic - seeing red and green (*can Martin confirm this?!)

Human
Trichromatic - seeing red, green and blue

**Comment by nebogeo** [comment]
I believe dichromatic vision is blue and yellow - they can't distinguish red and green (I googled and found our previous project ;)  http://nightjar.exeter.ac.uk/story/dichromat )

**Comment by FIONACH** [comment]
Thanks Dave. Dichromacy can change depending which cones they have - some dichromats have red and green, others have green and blue etc... I'm just not sure which the pollocks have!

On 3 Jun 2016, at 10:15, dave griffiths <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe dichromatic vision is blue and yellow - they can't distinguish red and green (I googled and found our previous project ;) http://nightjar.exeter.ac.uk/story/dichromat )

�

**Comment by nebogeo** [comment]
We should check with Martin, but that's how I'm processing the images for pollock-vision (replacing both the red and green channels with the average of them both)...

**Comment by FIONACH** [comment]
Ok great, thanks!

F

On 3 Jun 2016, at 11:18, dave griffiths <notifications@github.com<mailto:notifications@github.com>> wrote:

We should check with Martin, but that's how I'm processing the images for pollock-vision (replacing both the red and green channels with the average of them both)...

�

**Comment by nebogeo** [comment]
I've put in yellow/blue so I'll close this and get Martin to check it...
