### ISSUE TITLE
remove high scores?

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/crab-game#20]

**Comment by nebogeo** [comment]
I'd quite like to remove this as it's complexity somehow competing with the experiment results.

However, this is a very popular element for people in a public exhibition - so I think I'll remove it for now and see if it's a problem, we can fairly easily reinstate it...

**Comment by saramynott** [comment]
Is it slowing the game down? I agree that it it would be a great addition for those experiencing it during the exhibition, but if it's competing with the results, then it's worth removing it.

**Comment by nebogeo** [comment]
No it's just possibly adding confusion, just too many stats to take in really.
