### ISSUE TITLE
Switch the placing of next and quit?

### ISSUE THREAD

**Issue by saramynott** [nebogeo/crab-game#22]
Would it be possible to place 'Next' on the right and 'Quit' on the left of the screen when players move on to the next crab? Most programs/ processes give you the option of continuing on the right ('OK', 'Continue' buttons etc.) and cancelling on the left, so it might make continuing to play the game a more intuitive process.

**Comment by amberfoam** [comment]
Could remove option to quit?

**Comment by saramynott** [comment]
That could work, provided there's a time out that will take you back to the starting page. Otherwise, those who don't continue will leave the screen open and another player could start from where they left off, presenting problems for data collection.

**Comment by amberfoam** [comment]
Will be a timeout for the whole game - currently 2 mins I think...

**Comment by nebogeo** [comment]
yep the timeout is in now, I've swapped the buttons for the moment though, as this is totally correct
