### ISSUE TITLE
Clarify that there are 3 habitat types - text changes needed

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/crab-game#40]

**Comment by amberfoam** [comment]
On instruction page, could change text to:

'There is one crab hidden in every photo, touch it as soon as you see it'

to:

'You will see crabs that were found in rockpools, mudflats, and musselbeds against background photos of the three habitats.

There is one crab hidden in every photo, touch it as soon as you see it'

**Comment by FIONACH** [comment]
I think simply changing the names of the beaches/ares to the type of habitat will make this clear so you can leave the sentence as it is (just change touch to tap). Thanks
